MyAngularApiBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        username:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Type: string